apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    #kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  #InfluxDB has a UI that can be used to query, uncomment the `http` port and expose
  # to access this service
  #type: NodePort
  ports:
  # - name= http
  #   port: 80
  #   targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb
